In [1]:
import numpy as np

In [2]:
a1 = np.array([[1,2,3],[4,5,6]],dtype=np.int32).reshape(2,3)
a1

array([[1, 2, 3],
       [4, 5, 6]], dtype=int32)

In [3]:
a2 = np.float64(a1)
a2 , a2.dtype

(array([[1., 2., 3.],
        [4., 5., 6.]]), dtype('float64'))

In [4]:
a3 = np.int64(a1)
a3 , a3.dtype

(array([[1, 2, 3],
        [4, 5, 6]]), dtype('int64'))

In [5]:
a4 = np.str(a1)
a4 

'[[1 2 3]\n [4 5 6]]'

In [6]:
a5 = np.str(a4)
a5

'[[1 2 3]\n [4 5 6]]'

In [7]:
a6 = np.arange(0,12).reshape(4,3)
a6
a61 = a6[:1,]
a61

array([[0, 1, 2]])

In [8]:
a62 = a6[[3],]
a62

array([[ 9, 10, 11]])

In [9]:
a63 = a6[:,[1]]
a63

array([[ 1],
       [ 4],
       [ 7],
       [10]])

In [10]:
a64 = a6[1:3,0:2]
a64

array([[3, 4],
       [6, 7]])

In [11]:
a65 = a6[:,-1:]
a65

array([[ 2],
       [ 5],
       [ 8],
       [11]])

In [84]:
a7 = np.arange(11,51).reshape(8,5)
a7

array([[11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40],
       [41, 42, 43, 44, 45],
       [46, 47, 48, 49, 50]])

In [85]:
a7[a7%5==0] = 0
a7

array([[11, 12, 13, 14,  0],
       [16, 17, 18, 19,  0],
       [21, 22, 23, 24,  0],
       [26, 27, 28, 29,  0],
       [31, 32, 33, 34,  0],
       [36, 37, 38, 39,  0],
       [41, 42, 43, 44,  0],
       [46, 47, 48, 49,  0]])

In [86]:
a7[[0,1,2],[0,1,2]]

array([11, 17, 23])

In [108]:
a8 = np.arange(0,20).reshape(5,4)

In [88]:
def diagonal(ar):
    if ar.shape[0]==ar.shape[1]:
        for i in ar:
            for j in i:
                print ar[j][j]

In [89]:
diagonal(a8)

0
5
10
15


IndexError: index 4 is out of bounds for axis 0 with size 4

In [109]:
for a in a8.shape:
    print type(a)

<type 'int'>
<type 'int'>


In [113]:
for a in a8.shape:
    print a

5
4


In [92]:
# def n_o_Occu(ar):
c = 0
for i in a7:
    for j in i:
        #c += 1
        print j

11
12
13
14
0
16
17
18
19
0
21
22
23
24
0
26
27
28
29
0
31
32
33
34
0
36
37
38
39
0
41
42
43
44
0
46
47
48
49
0
