In [22]:
import numpy as np

In [23]:
l1 = [1,2,3,4,5]
a1 = np.array(l1)
a1, a1.size, a1.shape, a1.ndim, a1.dtype

(array([1, 2, 3, 4, 5]), 5, (5,), 1, dtype('int64'))

In [25]:
l2 = np.arange(1,6)
l3 = np.arange(2,7)
l4 = np.arange(4,9)

a2 = np.array(l2)
a3 = np.array(l3)
a4 = np.array(l4)

In [27]:
a2, a2.size, a2.shape, a2.ndim, a2.dtype

(array([1, 2, 3, 4, 5]), 5, (5,), 1, dtype('int64'))

In [28]:
a3, a3.size, a3.shape, a3.ndim, a3.dtype

(array([2, 3, 4, 5, 6]), 5, (5,), 1, dtype('int64'))

In [29]:
a4, a4.size, a4.shape, a4.ndim, a4.dtype

(array([4, 5, 6, 7, 8]), 5, (5,), 1, dtype('int64'))

In [31]:
a5 = np.ones((2,5,4))
a5, a5.size, a5.shape, a5.ndim, a5.dtype

(array([[[ 1.,  1.,  1.,  1.],
         [ 1.,  1.,  1.,  1.],
         [ 1.,  1.,  1.,  1.],
         [ 1.,  1.,  1.,  1.],
         [ 1.,  1.,  1.,  1.]],
 
        [[ 1.,  1.,  1.,  1.],
         [ 1.,  1.,  1.,  1.],
         [ 1.,  1.,  1.,  1.],
         [ 1.,  1.,  1.,  1.],
         [ 1.,  1.,  1.,  1.]]]), 40, (2, 5, 4), 3, dtype('float64'))

In [33]:
a6 = np.eye(4)
a6, a6.size, a6.shape, a6.ndim, a6.dtype

(array([[ 1.,  0.,  0.,  0.],
        [ 0.,  1.,  0.,  0.],
        [ 0.,  0.,  1.,  0.],
        [ 0.,  0.,  0.,  1.]]), 16, (4, 4), 2, dtype('float64'))

In [34]:
a7 = np.zeros_like(a5)
a7, a7.size, a7.shape, a7.ndim, a7.dtype

(array([[[ 0.,  0.,  0.,  0.],
         [ 0.,  0.,  0.,  0.],
         [ 0.,  0.,  0.,  0.],
         [ 0.,  0.,  0.,  0.],
         [ 0.,  0.,  0.,  0.]],
 
        [[ 0.,  0.,  0.,  0.],
         [ 0.,  0.,  0.,  0.],
         [ 0.,  0.,  0.,  0.],
         [ 0.,  0.,  0.,  0.],
         [ 0.,  0.,  0.,  0.]]]), 40, (2, 5, 4), 3, dtype('float64'))