In [43]:
import numpy as np

In [44]:
start = int(raw_input())
stop = int(raw_input())

0
9


In [49]:
a1 = np.arange(start,stop).reshape(int(raw_input()),int(raw_input()))
a1

5
6


ValueError: cannot reshape array of size 9 into shape (5,6)

In [34]:
a1

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [19]:
dn1 = int(raw_input())

2


In [40]:
a2 =(a1%dn1==0)
a1[a2]

array([0, 2, 4, 6, 8])

In [41]:
a3 =(a1%dn1!=0)
a1[a3]

array([1, 3, 5, 7])