In [20]:
import numpy as np
from numpy.linalg import inv

In [21]:
people = np.array([[3.0,3.2],[3.5,3.6]])
people

array([[ 3. ,  3.2],
       [ 3.5,  3.6]])

In [22]:
total = np.array([[118.4],[135.2]])
total

array([[ 118.4],
       [ 135.2]])

In [23]:
number = np.dot((inv(kids)),total)
number

array([[ 16.],
       [ 22.]])